/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TaskImport } from './routes/task'
import { Route as SigninImport } from './routes/signin'
import { Route as RefuelingImport } from './routes/refueling'
import { Route as CarImport } from './routes/car'
import { Route as IndexImport } from './routes/index'
import { Route as NoteIndexImport } from './routes/note/index'
import { Route as NoteNoteIdImport } from './routes/note/$noteId'
import { Route as NoteNoteIdSectionIdImport } from './routes/note_/$noteId/$sectionId'

// Create/Update Routes

const TaskRoute = TaskImport.update({
  id: '/task',
  path: '/task',
  getParentRoute: () => rootRoute,
} as any)

const SigninRoute = SigninImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any)

const RefuelingRoute = RefuelingImport.update({
  id: '/refueling',
  path: '/refueling',
  getParentRoute: () => rootRoute,
} as any)

const CarRoute = CarImport.update({
  id: '/car',
  path: '/car',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NoteIndexRoute = NoteIndexImport.update({
  id: '/note/',
  path: '/note/',
  getParentRoute: () => rootRoute,
} as any)

const NoteNoteIdRoute = NoteNoteIdImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => rootRoute,
} as any)

const NoteNoteIdSectionIdRoute = NoteNoteIdSectionIdImport.update({
  id: '/note_/$noteId/$sectionId',
  path: '/note/$noteId/$sectionId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/car': {
      id: '/car'
      path: '/car'
      fullPath: '/car'
      preLoaderRoute: typeof CarImport
      parentRoute: typeof rootRoute
    }
    '/refueling': {
      id: '/refueling'
      path: '/refueling'
      fullPath: '/refueling'
      preLoaderRoute: typeof RefuelingImport
      parentRoute: typeof rootRoute
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninImport
      parentRoute: typeof rootRoute
    }
    '/task': {
      id: '/task'
      path: '/task'
      fullPath: '/task'
      preLoaderRoute: typeof TaskImport
      parentRoute: typeof rootRoute
    }
    '/note/$noteId': {
      id: '/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof NoteNoteIdImport
      parentRoute: typeof rootRoute
    }
    '/note/': {
      id: '/note/'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof NoteIndexImport
      parentRoute: typeof rootRoute
    }
    '/note_/$noteId/$sectionId': {
      id: '/note_/$noteId/$sectionId'
      path: '/note/$noteId/$sectionId'
      fullPath: '/note/$noteId/$sectionId'
      preLoaderRoute: typeof NoteNoteIdSectionIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/car': typeof CarRoute
  '/refueling': typeof RefuelingRoute
  '/signin': typeof SigninRoute
  '/task': typeof TaskRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/note': typeof NoteIndexRoute
  '/note/$noteId/$sectionId': typeof NoteNoteIdSectionIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/car': typeof CarRoute
  '/refueling': typeof RefuelingRoute
  '/signin': typeof SigninRoute
  '/task': typeof TaskRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/note': typeof NoteIndexRoute
  '/note/$noteId/$sectionId': typeof NoteNoteIdSectionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/car': typeof CarRoute
  '/refueling': typeof RefuelingRoute
  '/signin': typeof SigninRoute
  '/task': typeof TaskRoute
  '/note/$noteId': typeof NoteNoteIdRoute
  '/note/': typeof NoteIndexRoute
  '/note_/$noteId/$sectionId': typeof NoteNoteIdSectionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/car'
    | '/refueling'
    | '/signin'
    | '/task'
    | '/note/$noteId'
    | '/note'
    | '/note/$noteId/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/car'
    | '/refueling'
    | '/signin'
    | '/task'
    | '/note/$noteId'
    | '/note'
    | '/note/$noteId/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/car'
    | '/refueling'
    | '/signin'
    | '/task'
    | '/note/$noteId'
    | '/note/'
    | '/note_/$noteId/$sectionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarRoute: typeof CarRoute
  RefuelingRoute: typeof RefuelingRoute
  SigninRoute: typeof SigninRoute
  TaskRoute: typeof TaskRoute
  NoteNoteIdRoute: typeof NoteNoteIdRoute
  NoteIndexRoute: typeof NoteIndexRoute
  NoteNoteIdSectionIdRoute: typeof NoteNoteIdSectionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarRoute: CarRoute,
  RefuelingRoute: RefuelingRoute,
  SigninRoute: SigninRoute,
  TaskRoute: TaskRoute,
  NoteNoteIdRoute: NoteNoteIdRoute,
  NoteIndexRoute: NoteIndexRoute,
  NoteNoteIdSectionIdRoute: NoteNoteIdSectionIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/car",
        "/refueling",
        "/signin",
        "/task",
        "/note/$noteId",
        "/note/",
        "/note_/$noteId/$sectionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/car": {
      "filePath": "car.tsx"
    },
    "/refueling": {
      "filePath": "refueling.tsx"
    },
    "/signin": {
      "filePath": "signin.tsx"
    },
    "/task": {
      "filePath": "task.tsx"
    },
    "/note/$noteId": {
      "filePath": "note/$noteId.tsx"
    },
    "/note/": {
      "filePath": "note/index.tsx"
    },
    "/note_/$noteId/$sectionId": {
      "filePath": "note_/$noteId/$sectionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
